### ISSUE TITLE
Facades problem

### ISSUE THREAD

**Issue by GeekTNT** [bluora/laravel-yandex-translate#3]
Laravel 5.4

I have installed according to the guides so (providers, aliases, key... triple-checked everything)

When I call the facade within the routes file ( /routes/web.php ) it works
```
Route::get('/test', function(){
    echo YandexTranslate::translate('Hello world', 'en', 'ru'); 
});
```

But when I want to use the same line of code (Facade) it in a controller it fails:
```
FatalThrowableError in HomeController.php line 95:
Class 'App\Http\Controllers\YandexTranslate' not found
```

The only way to use it is to add a \ before the Facade:
```
    echo \YandexTranslate::translate('Hello world', 'en', 'ru'); 
```

Got any ideas?
Thanks!

**Comment by RoccoHoward** [comment]
You need to add a class alias under your namespace declaration.

use YandexTranslate;

**Comment by GeekTNT** [comment]
LOOL

Works, thanks!
